### ISSUE TITLE
No module named 'preamble'

### ISSUE THREAD

**Issue by sumegim** [ML-course/engineer#1]
I have followed the instructions in the prerequisites notebook, but I get an error trying to run the Introduction. I get a No module named 'preamble' error, and I can't seem to find a solution online. 
![Screenshot from 2020-02-04 14-49-54](https://user-images.githubusercontent.com/22454710/73750781-169b5d00-475e-11ea-9f0a-2de921f3e74d.png)

**Comment by joaquinvanschoren** [comment]
preamble.py is a python file that should be in the notebook folder. It loads a bunch of packages so that you don’t have to add import commands all the time. You are probably trying to run the notebook in another folder and didn’t copy the preamble file?

**Comment by sumegim** [comment]
Yes, running the notebook with the preamble file in the same folder fixed it. Thank you for the quick reply.
