### ISSUE TITLE
Issue in notebook lecture 3 

### ISSUE THREAD

**Issue by nickvdw** [ML-course/engineer#6]
This is regarding `03 - Model Selection.ipynb`.

The cell directly under

> #### Model selection
>- Again, we can compare multiple models by looking at the ROC curves
> - We can calibrate the threshold depending on whether we need high recall or low FPR
> - We can select between algorithms (or hyperparameters) depending on the involved costs.

that plots the ROC curves for SVC and RF together with the thresholds (associated cell is `In [39]:` in the currently uploaded notebook) used

```python
plt.plot(fpr_rf[close_default_rf], tpr[close_default_rf], '^', markersize=10,
         label="threshold 0.5 RF", fillstyle="none", c='k', mew=2)
```

for plotting the RF threshold, but this should be

```python
plt.plot(fpr_rf[close_default_rf], tpr_rf[close_default_rf], '^', markersize=10,
         label="threshold 0.5 RF", fillstyle="none", c='k', mew=2)
```

instead, right?

**Comment by joaquinvanschoren** [comment]
Yes indeed!
Thanks for noticing it. I fixed it now.
